services:
  mongo:
    image: mongo:4.2.16-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: --auth
    volumes:
      - ./src/config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongo-data:/data/db

volumes:
  mongo-data:

